### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by nohsheef**
Missing `[`

### CODE REVIEW

**Comment by nohsheef** [comment]
What do you think about italicizing all parts within brackets? Would that be an improvement or too hard to read by the ticket author?

**Comment by yuuyins** [comment]
> What do you think about italicizing all parts within brackets? Would that be an improvement or too hard to read by the ticket author?

I think for the main fields italicizing is ok (just like that Reddit post), also taking into account

> span of text in an alternate voice or mood, or otherwise offset from the normal prose in a manner indicating a different quality of text
>
>---https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-i-element

But for the details/addendums, it is too much text that it is hard to read. I think instead of italics and brackets, we could add an horizontal rule like in https://github.com/yuuyinf/rustgig-gigs/blob/dev/.github/ISSUE_TEMPLATE/rust-job.md

Besides, I wonder in the future we should develop a "forms based" template like https://github.com/doomemacs/doomemacs/issues/new?assignees=&labels=is%3Abug%2Cneeds-triage&projects=&template=bug_report.yml (source https://github.com/doomemacs/doomemacs/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml)

**Comment by nohsheef** [comment]
Wow, a form would be ideal. Let's transform it into one!

Can we make it a form with nice features like a selection Onsite/Remote/Remote-Restricted/Custom. And maybe the description (wall of) text as placeholder of the text field which is automatically erased on first input? You know, like your regular input field in GUIs.

**Comment by nohsheef** [comment]
To reduce bus factor, I changed your role to _Owner_

**Comment by nohsheef** [comment]
I'll have a go at transforming the template into a form.

**Comment by nohsheef** [comment]
Supersesed by #3

**Pull request closed without merging**
